"use client";

import { ArrowLeft, BriefcaseBusiness, CalendarDays, CheckCircle2, FileSearch, FileText, Mail, Phone, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Page, PageHeader } from "@/components/ui/page-header";
import { useCompanies } from "@/lib/data";
import { demoEmployees, type Employee, type ResultStatus } from "@/lib/employees";
import { normalizeResultText, type ResultFinding, type ResultRecord } from "@/lib/results";
import { storageKeys, useStoredState } from "@/lib/storage";
import { initials } from "@/lib/utils";

const resultTone: Record<ResultStatus, "brand" | "warning" | "danger"> = { "Sonuç var": "brand", Bekliyor: "warning", Eksik: "danger" };

export default function EmployeeDetailPage({ employeeId }: { employeeId: number }) {
  const [companies] = useCompanies();
  const [storedEmployees] = useStoredState<Employee[]>(storageKeys.employees, demoEmployees);
  const [records] = useStoredState<ResultRecord[]>(storageKeys.resultRecords, []);
  const employees = storedEmployees.length ? storedEmployees : demoEmployees;
  const employee = employees.find((item) => item.id === employeeId) ?? null;

  if (!employee) {
    return <Page><Card className="p-10 text-center"><UserRound className="text-subtle mx-auto size-10" /><h1 className="text-heading mt-4 text-lg font-semibold">Personel bulunamadı</h1><p className="text-muted mt-1 text-sm">Bu kayıt silinmiş veya geçersiz bir bağlantı kullanılmış olabilir.</p><Button asChild className="mt-5" variant="secondary"><Link href="/personeller"><ArrowLeft /> Personellere dön</Link></Button></Card></Page>;
  }

  const company = companies.find((item) => item.id === employee.companyId);
  const employeeRecords = records.filter((record) => record.employeeId === employee.id || normalizeResultText(record.employeeName) === normalizeResultText(employee.name));
  const latestRecord = employeeRecords.at(-1);

  return <Page>
    <div className="mb-4 flex items-center justify-between gap-3"><Button asChild variant="ghost"><Link href="/personeller"><ArrowLeft /> Personellere dön</Link></Button><div className="flex gap-2"><Button asChild variant="secondary"><Link href="/sonuclar"><FileSearch /> Sonuç merkezine git</Link></Button><Button asChild><Link href={`/personeller?edit=${employee.id}`}><UserRound /> Düzenle</Link></Button></div></div>
    <PageHeader className="border-border bg-card shadow-card rounded-2xl border px-5 py-5 sm:px-6 sm:py-6" description={`${company?.name ?? "Firma belirtilmedi"} çalışan kaydı ve sağlık sonuçları.`} eyebrow="Çalışan detayları" title={employee.name} />
    <section className="border-brand/20 bg-brand-soft/30 shadow-card mt-5 rounded-2xl border p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="bg-card text-brand flex size-16 items-center justify-center rounded-2xl text-xl font-bold shadow-sm">{initials(employee.name)}</span><div><p className="text-heading text-lg font-semibold">{employee.name}</p><p className="text-muted mt-1 text-sm">{company?.name ?? "Firma belirtilmedi"} · {employee.department || "Departman belirtilmedi"}</p><p className="text-subtle mt-1 text-xs">{employee.position || "Görev belirtilmedi"}</p></div></div><Badge tone={resultTone[employee.lastResult]}>{employee.lastResult}</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Phone} label="Telefon" value={employee.phone || "Belirtilmedi"} /><Metric icon={Mail} label="E-posta" value={employee.email || "Belirtilmedi"} /><Metric icon={CalendarDays} label="Doğum tarihi" value={employee.birthDate || "Belirtilmedi"} /><Metric icon={ShieldCheck} label="Personel durumu" value={employee.status} /></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,0.6fr)]"><Card className="p-5"><SectionTitle icon={FileText} title="Sonuç geçmişi" subtitle={`${employeeRecords.length} rapor ve otomatik değerlendirme`} />{employeeRecords.length ? <div className="mt-4 space-y-3">{employeeRecords.slice().reverse().map((record) => <RecordCard key={record.id} record={record} />)}</div> : <EmptyResults />}</Card><div className="space-y-5"><Card className="p-5"><SectionTitle icon={BriefcaseBusiness} title="Çalışma bilgileri" subtitle="Personel kartındaki kayıtlı bilgiler" /><div className="mt-4 space-y-2"><Info label="Firma" value={company?.name ?? "Belirtilmedi"} /><Info label="Departman" value={employee.department || "Belirtilmedi"} /><Info label="Görev / unvan" value={employee.position || "Belirtilmedi"} /><Info label="Cinsiyet" value={employee.gender || "Belirtilmedi"} /></div></Card><Card className="p-5"><SectionTitle icon={CheckCircle2} title="Son durum" subtitle="En güncel sağlık sonucu" />{latestRecord ? <div className="bg-card-muted mt-4 rounded-xl p-4"><div className="flex items-center justify-between gap-2"><Badge tone={latestRecord.analysis.status === "attention" ? "danger" : latestRecord.analysis.status === "normal" ? "brand" : "warning"}>{latestRecord.analysis.status === "attention" ? "Dikkat" : latestRecord.analysis.status === "normal" ? "Normal" : "İncelenmeli"}</Badge><span className="text-subtle text-[11px]">{new Date(latestRecord.uploadedAt).toLocaleDateString("tr-TR")}</span></div><p className="text-muted mt-3 text-xs leading-5">{latestRecord.analysis.summary}</p></div> : <EmptyResults compact />}</Card></div></div>
  </Page>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Phone; label: string; value: string }) { return <div className="bg-card-muted flex min-w-0 items-center gap-3 rounded-xl p-3"><span className="bg-card text-brand flex size-9 shrink-0 items-center justify-center rounded-lg"><Icon className="size-4" /></span><div className="min-w-0"><p className="text-subtle text-[10px] font-bold tracking-[0.1em] uppercase">{label}</p><p className="text-heading mt-1 truncate text-xs font-semibold">{value}</p></div></div>; }
function SectionTitle({ icon: Icon, title, subtitle }: { icon: typeof FileText; title: string; subtitle: string }) { return <div className="flex items-center gap-3"><span className="bg-info-soft text-info flex size-9 items-center justify-center rounded-xl"><Icon className="size-4" /></span><div><h2 className="text-heading text-sm font-semibold">{title}</h2><p className="text-muted mt-0.5 text-xs">{subtitle}</p></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="bg-card-muted rounded-xl p-3"><p className="text-subtle text-[10px] font-bold tracking-[0.1em] uppercase">{label}</p><p className="text-heading mt-1 text-xs font-semibold">{value}</p></div>; }
function EmptyResults({ compact = false }: { compact?: boolean }) { return <div className={`border-border bg-card-muted/50 text-muted mt-4 rounded-xl border border-dashed ${compact ? "p-5" : "p-8"} text-center text-xs`}>Bu personel için henüz sonuç yüklenmemiş.</div>; }
function RecordCard({ record }: { record: ResultRecord }) { const tone = record.analysis.status === "attention" ? "danger" : record.analysis.status === "normal" ? "brand" : "warning"; return <article className="border-border rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="bg-info-soft text-info flex size-9 shrink-0 items-center justify-center rounded-lg"><FileText className="size-4" /></span><div className="min-w-0"><p className="text-heading truncate text-sm font-semibold">{record.fileName}</p><p className="text-muted mt-1 text-xs">{record.screeningType ?? "Diğer"} · {new Date(record.uploadedAt).toLocaleString("tr-TR")}</p></div></div><div className="flex items-center gap-2"><Badge tone={tone}>{record.analysis.status === "attention" ? "Dikkat" : record.analysis.status === "normal" ? "Normal" : "İncelenmeli"}</Badge>{record.dataUrl && <Button onClick={() => window.open(record.dataUrl, "_blank", "noopener,noreferrer")} size="sm" variant="secondary"><FileSearch /> PDF’i aç</Button>}</div></div><p className="text-muted bg-card-muted mt-3 rounded-lg p-3 text-xs leading-5">{record.analysis.summary}</p>{record.analysis.findings.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{record.analysis.findings.map((finding) => <Finding key={finding.label} finding={finding} />)}</div> : null}</article>; }
function Finding({ finding }: { finding: ResultFinding }) { const tone = finding.status === "normal" ? "brand" : finding.status === "review" ? "warning" : "danger"; return <div className="bg-card-muted rounded-lg p-3"><div className="flex items-center justify-between gap-2"><span className="text-heading text-xs font-semibold">{finding.label}</span><Badge tone={tone}>{finding.status === "normal" ? "Normal" : finding.status === "low" ? "Düşük" : finding.status === "high" ? "Yüksek" : "İncele"}</Badge></div><p className="text-muted mt-1 text-xs">{finding.value} {finding.unit} · {finding.reference}</p></div>; }
