"use client";

import { FileText, ScrollText } from "lucide-react";
import { useState } from "react";
import { Textarea } from "@/components/ui/field";

export function ScreeningDocuments({ coverLetter, conditions, mode, update }: { coverLetter: string; conditions: string; mode?: "coverLetter" | "conditions"; update: (key: "coverLetter" | "conditions", value: string) => void }) {
  const [tab, setTab] = useState<"coverLetter" | "conditions">(mode ?? "coverLetter");
  const templates = { coverLetter: "Sayın Yetkili,\n\nFirmanız çalışanlarının sağlığını desteklemek amacıyla planlanan saha taraması kapsamında, seçilen hizmetleri ve uygulama takvimini aşağıda bilgilerinize sunarız. Süreç, uzman ekibimiz ve uygun ekipmanlarımızla güvenli ve düzenli şekilde yürütülecektir.\n\nSorularınız için bizimle iletişime geçebilirsiniz.\n\nSaygılarımızla,", conditions: "1. Tarama, planlanan tarih ve saha konumunda gerçekleştirilir.\n\n2. Katılımcı listesi ve saha hazırlıkları firma tarafından tarama öncesinde paylaşılır.\n\n3. Raporlama, hizmet tamamlandıktan sonra kurumun belirlediği yetkililere teslim edilir.\n\n4. Kişisel veriler ve sağlık bilgileri yürürlükteki mevzuata uygun şekilde korunur." };
  const value = tab === "coverLetter" ? coverLetter : conditions;
  return <section className="mt-6 rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-foreground">Ön yazı ve şartlar</p><p className="mt-1 text-[11px] text-muted">Tekliflerdeki metin yapısıyla uyumlu olarak tarama planına özel açıklamalar ekleyin.</p></div><button className="rounded-lg border border-border px-2.5 py-1 text-[10px] font-semibold text-muted hover:border-brand-outline hover:text-brand" onClick={() => update(tab, templates[tab])} type="button">Şablonu kullan</button></div><div className={`mt-4 flex gap-1 rounded-xl bg-card-muted p-1 ${mode ? "hidden" : ""}`}><button className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold ${tab === "coverLetter" ? "bg-card text-brand shadow-sm" : "text-muted"}`} onClick={() => setTab("coverLetter")} type="button"><FileText className="size-3.5" /> Ön yazı</button><button className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold ${tab === "conditions" ? "bg-card text-brand shadow-sm" : "text-muted"}`} onClick={() => setTab("conditions")} type="button"><ScrollText className="size-3.5" /> Şartlar ve koşullar</button></div><Textarea className="mt-3 min-h-44 text-xs leading-6" onChange={(event) => update(tab, event.target.value)} placeholder={tab === "coverLetter" ? "Taramanın amacı ve kapsamını anlatan ön yazı..." : "Tarama şartları, hazırlıklar ve teslim koşulları..."} value={value} /></section>;
}
